/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "eeprom.h"
#include "usart.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	char str[32];
	int choice;
	SystemInit();
	UartInit(BAUD_9600);
	EEPROM_Init();
	do
	{
		UartPuts("enter choice\r\n");
		UartPuts("1 write a string into EEPROM at address 0x0000\r\n");
		UartPuts("2 read 32 bytes from from address 0x0000\r\n");
		UartGets(str);
		sscanf(str, "%d",&choice);
		switch(choice)
		{
			case 1 :
				sscanf(str,"enter string%s\r\n",str);
	        	UartGets(str);
				EEPROM_Write(0x0020, (uint8_t*)str, 32);
				break;
			case 2 :
				sprintf(str,"string are\r\n");
				EEPROM_Read(0x0020, (uint8_t*)str, 32);
				UartPuts(str);
				break;
	      }
	}
		while(choice!=0);
		return 0;

    while(1);
	return 0;
}
